services:
    bus-stop-ar:
        build: .
        container_name: bus-stop-ar
        ports:
            - "8090:80"
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - busstopar_net

networks:
    busstopar_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.212.0.0/16
